homepage/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *
app_name = 'homepage'

urlpatterns = [
	url(r"^deleteurl/(?P<delete_id>\d+)/$",delete, name='delete'),
    path('',about, name='about'),
	path('organizations',organizations, name='organizations'),
	path('educations',educations, name='educations'),
	path('experiences',experiences, name='experiences'),
	path('schedule/',schedule, name='schedule'),
    path('schedule/create', schedule_create, name='schedule_create'),
    path('schedule/delete', schedule_delete, name='schedule_delete'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin', admin.site.urls),
	path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return "{}. {}".format(self.id, self.activity)

homepage/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'activity':forms.TextInput(attrs={'placeholder':'Masukkan nama kegiatan'}),
            'place':forms.TextInput(attrs={'placeholder':'Masukkan nama tempat'}),
            'category':forms.TextInput(attrs={'placeholder':'Masukkan nama kategori'}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms


# Create your views here.
def about(request):
    return render(request, 'about.html')
def educations(request):
    return render(request, 'educations.html')
def organizations(request):
    return render(request, 'organizations.html')
def experiences(request):
    return render(request, 'experiences.html')
def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request):
	Schedule.objects.all().delete()
	return render(request, "schedule.html")

def delete(request, delete_id):
	Schedule.objects.filter(id=delete_id).delete()
	return redirect('homepage:schedule')

homepage/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>First Drip by heavenfreesta</title>
    <style>
    .con1{
         background: url("{% static 'images/background1.jpg' %}") no-repeat center center black;
    }
    </style>
</head>
<body>
    <div class="">
        <div class="container-fluid con1">
            <div class="row row2">
                <div class="text-center w-100" style="margin-top: 10rem;">
                    <img class="img-center image" src="{% static 'images/FIRST_DRIP.png' %}" style="width: 80%; object-fit: scale-down;">
                </div>
            </div>
            <div class="row row1">
                <div class="button p-4">
                    <div class="btn-group-vertical">
                        <a  href="{% url 'homepage:about' %}"><button type="button" class="btn btn-light ">ABOUT</button></a>
                        <a  href="{% url 'homepage:organizations' %}"><button type="button" class="btn btn-light ">ORGANIZATIONS</button></a>
                        <a  href="{% url 'homepage:educations' %}"><button type="button" class="btn btn-light ">EDUCATIONS</button></a>
                        <a  href="{% url 'homepage:experiences' %}"><button type="button" class="btn btn-light ">EXPERIENCES</button></a>
                        <a  href="{% url 'homepage:schedule' %}"><button type="button" class="btn btn-light ">SCHEDULES</button></a>
                    </div>
                </div>  
            </div>
        </div>
    </div>
    <div class="">
        <div class="container-fluid bg-black">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-left p-3">
                        <p>About</p>
                    <div class="hline"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="body-pic">
                        <img class="img" src="{% static 'images/BodyPic.jpg' %}">
                    </div>
                </div>
                <div class="col">
                    <div class="body-text">
                        <p>I’m a first year student in Faculty of Computer Science in University of Indonesia. Interested in any kind of sports and any kind of music (except traditional dangdut). Product manager wannabe.</p>
                    </div>
                </div>
            </div>
            <div class="row last-row">
                <div class="col-lg-9">
          
                </div>
                <div class="col-xs-1 fb">
                    <div class="facebook">
                        <a href="https://www.facebook.com/akhmad.dw">
                        <img src="{% static 'images/FC.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 tw">
                    <div class="twitter">
                        <a href="https://www.twitter.com/akhmadiponegoro">
                        <img src="{% static 'images/TW.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 ig">
                    <div class="insta">
                        <a href="https://www.instagram.com/akhmadiponegoro/">
                        <img src="{% static 'images/IG.png' %}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/educations.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>First Drip by heavenfreesta</title>
    <style>
    .con1{
         background: url("{% static 'images/background1.jpg' %}") no-repeat center center black;
    }
    </style>
</head>
<body>
    <div class="">
        <div class="container-fluid con1">
            <div class="row row2">
                <div class="text-center w-100" style="margin-top: 10rem;">
                    <img class="img-center image" src="{% static 'images/FIRST_DRIP.png' %}" style="width: 80%; object-fit: scale-down;">
                </div>
            </div>
            <div class="row row1">
                <div class="button p-4">
                        <div class="btn-group-vertical">
                                <a  href="{% url 'homepage:about' %}"><button type="button" class="btn btn-light ">ABOUT</button></a>
                                <a  href="{% url 'homepage:organizations' %}"><button type="button" class="btn btn-light ">ORGANIZATIONS</button></a>
                                <a  href="{% url 'homepage:educations' %}"><button type="button" class="btn btn-light ">EDUCATIONS</button></a>
                                <a  href="{% url 'homepage:experiences' %}"><button type="button" class="btn btn-light ">EXPERIENCES</button></a>
                                <a  href="{% url 'homepage:schedule' %}"><button type="button" class="btn btn-light ">SCHEDULES</button></a>
                            </div>
                </div>  
            </div>
        </div>
    </div>
    <div class="">
        <div class="container-fluid bg-black">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-left p-3">
                        <p>Educations</p>
                    <div class="hline"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="body-text">
                            <p>TK Islam Fitrah Al-Fikri Depok - 2005</p>
                            <p>SD Negeri Cimahi Mandiri 3 - 2012</p>
                            <p>SMP Negeri 1 Cimahi - 2015</p>
                            <p>SMA Negeri 2 Bandung - 2018</p>
                            <p>Fakultas Ilmu Komputer Universitas Indonesia - 2018</p>
                    </div>
                </div>
            </div>
            <div class="row last-row">
                <div class="col-lg-9">
          
                </div>
                <div class="col-xs-1 fb">
                    <div class="facebook">
                        <a href="https://www.facebook.com/akhmad.dw">
                        <img src="{% static 'images/FC.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 tw">
                    <div class="twitter">
                        <a href="https://www.twitter.com/akhmadiponegoro">
                        <img src="{% static 'images/TW.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 ig">
                    <div class="insta">
                        <a href="https://www.instagram.com/akhmadiponegoro/">
                        <img src="{% static 'images/IG.png' %}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/experiences.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>First Drip by heavenfreesta</title>
    <style>
    .con1{
         background: url("{% static 'images/background1.jpg' %}") no-repeat center center black;
    }
    </style>
</head>
<body>
    <div class="">
        <div class="container-fluid con1">
            <div class="row row2">
                <div class="text-center w-100" style="margin-top: 10rem;">
                    <img class="img-center image" src="{% static 'images/FIRST_DRIP.png' %}" style="width: 80%; object-fit: scale-down;">
                </div>
            </div>
            <div class="row row1">
                <div class="button p-4">
                        <div class="btn-group-vertical">
                                <a  href="{% url 'homepage:about' %}"><button type="button" class="btn btn-light ">ABOUT</button></a>
                                <a  href="{% url 'homepage:organizations' %}"><button type="button" class="btn btn-light ">ORGANIZATIONS</button></a>
                                <a  href="{% url 'homepage:educations' %}"><button type="button" class="btn btn-light ">EDUCATIONS</button></a>
                                <a  href="{% url 'homepage:experiences' %}"><button type="button" class="btn btn-light ">EXPERIENCES</button></a>
                                <a  href="{% url 'homepage:schedule' %}"><button type="button" class="btn btn-light ">SCHEDULES</button></a>
                            </div>
                </div>  
            </div>
        </div>
    </div>
    <div class="">
        <div class="container-fluid bg-black">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-left p-3">
                        <p>Experiences</p>
                    <div class="hline"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="body-text-2">
                        <p>> Staff of Public Relations [EDUCARE 2019]</p>
                        <p>Dec 2019 - Apr 2019</p>
                        <p>> Staff of Health and Fundraising [CS League 2019]</p>
                        <p>Jan 2019 - Apr 2019</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="body-text-3">
                        <p>> Staff of Stage [COMPFEST 11]</p>
                        <p>Feb 2019 - Sep 2019</p>
                        <p>> Data Analyst Intern [PT Karpa Imaji Labs]</p>
                        <p>Jul 2019 - Aug 2019</p>
                    </div>
                </div>
            </div>
            <div class="row last-row">
                <div class="col-lg-9">
          
                </div>
                <div class="col-xs-1 fb">
                    <div class="facebook">
                        <a href="https://www.facebook.com/akhmad.dw">
                        <img src="{% static 'images/FC.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 tw">
                    <div class="twitter">
                        <a href="https://www.twitter.com/akhmadiponegoro">
                        <img src="{% static 'images/TW.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 ig">
                    <div class="insta">
                        <a href="https://www.instagram.com/akhmadiponegoro/">
                        <img src="{% static 'images/IG.png' %}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/organizations.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>First Drip by heavenfreesta</title>
    <style>
    .con1{
         background: url("{% static 'images/background1.jpg' %}") no-repeat center center black;
    }
    </style>
</head>
<body>
    <div class="">
        <div class="container-fluid con1">
            <div class="row row2">
                <div class="text-center w-100" style="margin-top: 10rem;">
                    <img class="img-center image" src="{% static 'images/FIRST_DRIP.png' %}" style="width: 80%; object-fit: scale-down;">
                </div>
            </div>
            <div class="row row1">
                <div class="button p-4">
                        <div class="btn-group-vertical">
                                <a  href="{% url 'homepage:about' %}"><button type="button" class="btn btn-light ">ABOUT</button></a>
                                <a  href="{% url 'homepage:organizations' %}"><button type="button" class="btn btn-light ">ORGANIZATIONS</button></a>
                                <a  href="{% url 'homepage:educations' %}"><button type="button" class="btn btn-light ">EDUCATIONS</button></a>
                                <a  href="{% url 'homepage:experiences' %}"><button type="button" class="btn btn-light ">EXPERIENCES</button></a>
                                <a  href="{% url 'homepage:schedule' %}"><button type="button" class="btn btn-light ">SCHEDULES</button></a>
                            </div>
                </div>  
            </div>
        </div>
    </div>
    <div class="">
        <div class="container-fluid bg-black">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-left p-3">
                        <p>Organizations</p>
                    <div class="hline"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="body-pic-1">
                        <img class="img" src="{% static 'images/Gambar_RS2.png' %}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="body-text-1">
                        <p>Rumah Seni 2 (SMA Negeri 2 Bandung)</p>
                        <p> Ketua Div. Ansamble</p><br>
                        <p>SISTEM Fasilkom UI</p>
                        <p>Member of Entrepreneurship SIG</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="body-pic-2">
                        <img class="img" src="{% static 'images/Gambar_SISTEM.png' %}">
                    </div>
                </div>
            </div>
            <div class="row last-row">
                <div class="col-lg-9">
          
                </div>
                <div class="col-xs-1 fb">
                        <div class="facebook">
                            <a href="https://www.facebook.com/akhmad.dw">
                            <img src="{% static 'images/FC.png' %}"></a>
                        </div>
                    </div>
                    <div class="col-xs-1 tw">
                        <div class="twitter">
                            <a href="https://www.twitter.com/akhmadiponegoro">
                            <img src="{% static 'images/TW.png' %}"></a>
                        </div>
                    </div>
                    <div class="col-xs-1 ig">
                        <div class="insta">
                            <a href="https://www.instagram.com/akhmadiponegoro/">
                            <img src="{% static 'images/IG.png' %}"></a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/schedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>First Drip by heavenfreesta</title>
    <style>
    .con1{
         background: url("{% static 'images/background1.jpg' %}") no-repeat center center black;
    }
    .tag{
        color: white;
    }
    </style>
</head>
<body>
    <div class="">
        <div class="container-fluid con1">
            <div class="row row2">
                <div class="text-center w-100" style="margin-top: 10rem;">
                    <img class="img-center image" src="{% static 'images/FIRST_DRIP.png' %}" style="width: 80%; object-fit: scale-down;">
                </div>
            </div>
            <div class="row row1">
                <div class="button p-4">
                        <div class="btn-group-vertical">
                                <a  href="{% url 'homepage:about' %}"><button type="button" class="btn btn-light ">ABOUT</button></a>
                                <a  href="{% url 'homepage:organizations' %}"><button type="button" class="btn btn-light ">ORGANIZATIONS</button></a>
                                <a  href="{% url 'homepage:educations' %}"><button type="button" class="btn btn-light ">EDUCATIONS</button></a>
                                <a  href="{% url 'homepage:experiences' %}"><button type="button" class="btn btn-light ">EXPERIENCES</button></a>
                                <a  href="{% url 'homepage:schedule' %}"><button type="button" class="btn btn-light ">SCHEDULES</button></a>
                            </div>
                </div>  
            </div>
        </div>
    </div>
    <div class="">
        <div class="container-fluid bg-black">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-left p-3">
                        <p>Schedules</p>
                    <div class="hline"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <table class="table tag">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Tanggal</th>
                        <th scope="col">Jam</th>
                        <th scope="col">Nama Kegiatan</th>
                        <th scope="col">Tempat</th>
                        <th scope="col">Kategori</th>
                        <th scope="col">Hapus</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for schedule in schedules %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{ schedule.date.date }}</td>
                                <td>{{ schedule.time}}</td>
                                <td>{{ schedule.activity }}</td>
                                <td>{{ schedule.place }}</td>
                                <td>{{ schedule.category }}</td>
                                <td><a class="btn btn-danger" href="{% url 'homepage:delete' schedule.id %}" >Delete</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
            <div class="row">
                <div class= 'col-lg-2'>

                </div>
                <div class = 'col-lg-10'>
                    <div class = 'form-group'>
                        <a href="{% url 'homepage:schedule_delete' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Clear</button></a>
                        <a href="{% url 'homepage:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>
                    </div>
                </div>
            </div>
            <div class="row last-row">
                <div class="col-lg-9">
          
                </div>
                <div class="col-xs-1 fb">
                    <div class="facebook">
                        <a href="https://www.facebook.com/akhmad.dw">
                        <img src="{% static 'images/FC.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 tw">
                    <div class="twitter">
                        <a href="https://www.twitter.com/akhmadiponegoro">
                        <img src="{% static 'images/TW.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 ig">
                    <div class="insta">
                        <a href="https://www.instagram.com/akhmadiponegoro/">
                        <img src="{% static 'images/IG.png' %}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/schedule_create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>First Drip by heavenfreesta</title>
    <style>
    .con1{
         background: url("{% static 'images/background1.jpg' %}") no-repeat center center black;
    }
    .tag{
        color: white;
    }
    </style>
</head>
<body>
    <div class="">
        <div class="container-fluid con1">
            <div class="row row2">
                <div class="text-center w-100" style="margin-top: 10rem;">
                    <img class="img-center image" src="{% static 'images/FIRST_DRIP.png' %}" style="width: 80%; object-fit: scale-down;">
                </div>
            </div>
            <div class="row row1">
                <div class="button p-4">
                        <div class="btn-group-vertical">
                                <a  href="{% url 'homepage:about' %}"><button type="button" class="btn btn-light ">ABOUT</button></a>
                                <a  href="{% url 'homepage:organizations' %}"><button type="button" class="btn btn-light ">ORGANIZATIONS</button></a>
                                <a  href="{% url 'homepage:educations' %}"><button type="button" class="btn btn-light ">EDUCATIONS</button></a>
                                <a  href="{% url 'homepage:experiences' %}"><button type="button" class="btn btn-light ">EXPERIENCES</button></a>
                                <a  href="{% url 'homepage:schedule' %}"><button type="button" class="btn btn-light ">SCHEDULES</button></a>
                            </div>
                </div>  
            </div>
        </div>
    </div>
    <div class="">
        <div class="container-fluid bg-black">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-left p-3">
                        <p>Schedules</p>
                    <div class="hline"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <form class="css" action="{% url 'homepage:schedule_create' %}" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-sm-1"></div>
                            <div class="form-group col-sm-10 tag">
                                {% for fields in form %}
                                    {{ fields.label_tag }}
                                    <br>
                                    {{ fields }}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-sm-1"></div>
                            <input type="submit" class="btn btn-primary float-right" value="Add">
                        </div>
                    </form>                
                </div>
            </div>
            <div class="row last-row">
                <div class="col-lg-9">
          
                </div>
                <div class="col-xs-1 fb">
                    <div class="facebook">
                        <a href="https://www.facebook.com/akhmad.dw">
                        <img src="{% static 'images/FC.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 tw">
                    <div class="twitter">
                        <a href="https://www.twitter.com/akhmadiponegoro">
                        <img src="{% static 'images/TW.png' %}"></a>
                    </div>
                </div>
                <div class="col-xs-1 ig">
                    <div class="insta">
                        <a href="https://www.instagram.com/akhmadiponegoro/">
                        <img src="{% static 'images/IG.png' %}"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>